# File: .github/workflows/azure-python-deploy.yml

name: Build and deploy Python app to Azure Web App - unifiedgymmanager

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r backend/requirements.txt  # Updated path

      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)
      - name: Run Django tests
        run: |
          source venv/bin/activate
          python backend/manage.py test

      - name: Zip artifact for deployment
        run: |
          zip release.zip ./* -r
          echo "Zipped all files"

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            release.zip
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_063D085DA26843B398E9EB4C7D8F71CA }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_1E3BAA3A501E46C6843AE64FE0F0C7B7 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_3FFFC561E8AA4839B1DCC6D04B072DCE }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'unifiedgymmanager'
          slot-name: 'Production'
